### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by maggieezzat** [tblock/thesis-data#1]
Hello, I would like to know the results you got using each classifier, and if there are any state of the art results that one can compare to.

**Comment by tblock** [comment]
I shared my results on the [fast.ai forums](https://forums.fast.ai/t/ulmfit-german/22529/88). My Thesis is written in German. I'd share it, if you have use for it. 

I'm not aware of any other work on the 10kGNAD, but I'm not actively following research. 

For reference https://github.com/tblock/10kGNAD/issues/2
